# Trading Persona Analyzer Configuration

ollama:
  base_url: "http://192.168.1.14:11434"
  model: "gpt-oss:20b-32k"
  temperature: 0.7
  top_p: 0.9
  max_tokens: 4096

postgres:
  host: "localhost"
  port: 5432
  database: "trading_ai"
  user: "postgres"
  password: "postgres"


data:
  required_columns:
    - Scrip Name
    - Buy Date
    - Buy Rate
    - Sell Date
    - Sell Rate
    - Quantity
    - Profit(+) / Loss(-)
    - Trade Type

metrics:
  risk_free_rate: 0.065
  trading_days_per_year: 252

analysis:
  min_trades_for_pattern: 10
  lookback_period_days: 180
  confidence_threshold: 0.7

report:
  output_format: ["html", "json"]
  include_charts: true
  chart_style: "seaborn"